name: dlox
description: A Dart port of the Lox language interpreter (http://www.craftinginterpreters.com/).
author: Ross Kirsling <rkirsling@gmail.com>
homepage: https://github.com/rkirsling/dlox
dependencies:
  charcode: ^1.1.2
dev_dependencies:
  yaml: ^2.1.15
executables:
  dlox: main
